---

- name: Configure Base Configs
  hosts: site1
  connection: local
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  roles:
    - asr1k_mgmt

- name: Run a Second Time because you need to
  hosts: site1
  connection: local
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  roles:
    - asr1k_mgmt
