---

- name: Wipe configs
  hosts: site1
  connection: local
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  roles:
    - asr1k_wipe
