hostname: CO-asr1k-1
device_type: asr1k

mgmt_interface: GigabitEthernet0
mgmt_mask: 255.255.255.128

old_ver: bootflash:/asr1001x-universalk9.03.17.03.S.156-1.S3-std.SPA.bin
old_config: old_base.cfg
new_ver: bootflash:/asr1001x-universalk9.03.17.04.S.156-1.S4-std.SPA.bin
new_config: new_base.cfg

ospf_process: 1
router_id: "1.1.1.1"

interfaces:
  - name: GigabitEthernet0/0/0
    description: LAN
    ip: "192.168.0.1"
    netmask: "255.255.255.0"
    cdp: True
    ospf_area: 0
  - name: GigabitEthernet0/0/1
    description: WAN
    ip: "172.16.0.1"
    netmask: "255.255.255.0"
    cdp: True
    ospf_area: 0
  - name: Loopback0
    description: RouterID
    ip: "{{ router_id }}"
    netmask: "255.255.255.255"
    cdp: False
    ospf_area: 0
    ospf_passive: True

vrfs:
  - Mgmt-intf

routes:
  - vrf: Mgmt-intf
    network: 0.0.0.0
    mask: 0.0.0.0
    next_hop: 10.94.167.126
