---

- name: Get out of Q&A Prompt on {{ hostname }}
  shell: |
    spawn telnet {{ remote_addr }} {{ remote_port }}
    sleep 1
    send "\n\n\n"
    expect {
      ": " {
        send "no\n"
        sleep 1
        send "\n\n"
        sleep 2
        send "\n\n"
      }
      "Router>" {
        send "enable\n"
      }
      "#" {
        send "terminal length 0\n"
      }
    }
  args:
    executable: expect

- name: Configure SSH access via Telnet on Terminal server
  shell: |
    spawn telnet {{ remote_addr }} {{ remote_port }}
    send "\n"
    send "enable\n"

    expect "#"
    send "configure terminal\n"

    expect "#"
    send "hostname {{ hostname }}\n"
    send "ip domain-name {{ domain_name }}\n"
    send "crypto key generate rsa modulus 2048\n"
    send "username {{ username }} privilege 15 password {{ enable_password }}\n"
    send "enable secret {{ enable_password }}\n"
    send "line vty 0 4\n"
    send "transport input ssh telnet\n"
    send "password cisco\n"
    send "login local\n"
    send "privilege level 15\n"
    send "interface {{ mgmt_interface }}\n"
    send "description mgmt\n"
    send "ip address {{ ansible_host }} {{ mgmt_mask }}\n"
    send "no shutdown\n"
    send "exit\n"
    {% for route in routes %}
      send "ip route vrf {{ route.vrf }} {{ route.network }} {{ route.mask }} {{ route.next_hop }}\n"
    {% endfor %}
    send "end\n"
  args:
    executable: expect
